import { Request, Response, NextFunction } from 'express';
import prisma from '../prisma';

/** List locations — filterable by categoryId, supports pagination */
export async function getLocations(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const userId = req.user!.id;
    const { categoryId, search, page = '1', limit = '50' } = req.query as Record<string, string>;

    const pageNum = Math.max(1, parseInt(page, 10) || 1);
    const limitNum = Math.min(100, Math.max(1, parseInt(limit, 10) || 50));
    const skip = (pageNum - 1) * limitNum;

    const where: Record<string, unknown> = { createdByUserId: userId };
    if (categoryId) where['categoryId'] = parseInt(categoryId, 10);
    if (search) where['name'] = { contains: search };

    const [data, total] = await Promise.all([
      prisma.location.findMany({
        where,
        include: { category: true },
        orderBy: { createdAt: 'desc' },
        skip,
        take: limitNum,
      }),
      prisma.location.count({ where }),
    ]);

    res.json({ data, total, page: pageNum, limit: limitNum });
  } catch (error) {
    next(error);
  }
}

/** Get a single location by its unique QR code — PUBLIC endpoint (no auth required) */
export async function getLocationByCode(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const code = req.params['code'] as string;

    const location = await prisma.location.findUnique({
      where: { uniqueCode: code },
      include: {
        category: true,
        visits: {
          orderBy: { dateTimestamp: 'desc' },
          take: 10,
          include: { user: { select: { id: true, name: true } } },
        },
      },
    });

    if (!location) {
      res.status(404).json({ error: 'Ubicación no encontrada' });
      return;
    }

    res.json(location);
  } catch (error) {
    next(error);
  }
}

/** Get a single location by ID */
export async function getLocationById(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const userId = req.user!.id;
    const locationId = parseInt(req.params['id'] as string, 10);

    const location = await prisma.location.findUnique({
      where: { id: locationId },
      include: {
        category: true,
        collectionLocations: {
          include: { collection: { select: { id: true, name: true } } },
        },
        _count: { select: { visits: true } },
      },
    });

    if (!location || location.createdByUserId !== userId) {
      res.status(404).json({ error: 'Ubicación no encontrada' });
      return;
    }

    res.json(location);
  } catch (error) {
    next(error);
  }
}

/** Create a new location with optional image */
export async function createLocation(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const userId = req.user!.id;
    const body = req.body as Record<string, string>;
    const name = body['name'] ?? '';
    const latitude = parseFloat(body['latitude'] ?? '');
    const longitude = parseFloat(body['longitude'] ?? '');
    const categoryId = parseInt(body['categoryId'] ?? '', 10);

    if (!name.trim() || isNaN(latitude) || isNaN(longitude) || isNaN(categoryId)) {
      res.status(400).json({ error: 'Datos inválidos: nombre, latitud, longitud y categoría son requeridos' });
      return;
    }

    // Verify the category belongs to the user
    const category = await prisma.category.findUnique({ where: { id: categoryId } });
    if (!category || category.createdByUserId !== userId) {
      res.status(400).json({ error: 'Categoría no válida' });
      return;
    }

    // Handle uploaded image
    const imageUrl = req.file ? `/uploads/${req.file.filename}` : null;

    const location = await prisma.location.create({
      data: {
        name,
        latitude,
        longitude,
        categoryId,
        imageUrl,
        createdByUserId: userId,
        // uniqueCode is auto-generated by Prisma @default(uuid())
      },
      include: { category: true },
    });

    res.status(201).json(location);
  } catch (error) {
    next(error);
  }
}

/** Update a location */
export async function updateLocation(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const userId = req.user!.id;
    const locationId = parseInt(req.params['id'] as string, 10);
    const body = req.body as Record<string, string>;
    const name = body['name'];
    const latitude = body['latitude'] !== undefined ? parseFloat(body['latitude']) : undefined;
    const longitude = body['longitude'] !== undefined ? parseFloat(body['longitude']) : undefined;
    const categoryId = body['categoryId'] !== undefined ? parseInt(body['categoryId'], 10) : undefined;

    // Verify ownership
    const location = await prisma.location.findUnique({ where: { id: locationId } });
    if (!location || location.createdByUserId !== userId) {
      res.status(404).json({ error: 'Ubicación no encontrada' });
      return;
    }

    // Verify category if changed
    if (categoryId !== undefined) {
      const category = await prisma.category.findUnique({ where: { id: categoryId } });
      if (!category || category.createdByUserId !== userId) {
        res.status(400).json({ error: 'Categoría no válida' });
        return;
      }
    }

    // Handle image update
    const imageUrl = req.file ? `/uploads/${req.file.filename}` : undefined;

    const updated = await prisma.location.update({
      where: { id: locationId },
      data: {
        ...(name !== undefined && { name }),
        ...(latitude !== undefined && { latitude }),
        ...(longitude !== undefined && { longitude }),
        ...(categoryId !== undefined && { categoryId }),
        ...(imageUrl !== undefined && { imageUrl }),
      },
      include: { category: true },
    });

    res.json(updated);
  } catch (error) {
    next(error);
  }
}

/** Delete a location */
export async function deleteLocation(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const userId = req.user!.id;
    const locationId = parseInt(req.params['id'] as string, 10);

    const location = await prisma.location.findUnique({ where: { id: locationId } });
    if (!location || location.createdByUserId !== userId) {
      res.status(404).json({ error: 'Ubicación no encontrada' });
      return;
    }

    // Cascade deletes will handle collectionLocations and visits
    await prisma.location.delete({ where: { id: locationId } });
    res.status(204).send();
  } catch (error) {
    next(error);
  }
}
